services:
  - type: web
    name: upskill-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000